Repository operate-first/argocd-apps, pull requests merged in 2020-12, with the labels that each got.

#13 feat: Add data catalog and dashboard apps
  odh/dashboard.yaml
  odh/datacatalog.yaml
  odh/kustomization.yaml
Labels: approved, size/M

#14 Restructured repo to accomodate environments
  base/data-science/kustomization.yaml
  base/operate-first/argo.yaml
  base/operate-first/dashboard.yaml
  base/operate-first/datacatalog.yaml
  base/operate-first/jupyterhub.yaml
  base/operate-first/kustomization.yaml
  base/operate-first/monitoring.yaml
  base/operate-first/superset.yaml
  base/thoth/kustomization.yaml
  create-project.sh
  docs/add_application.md
  docs/add_project.md
  kustomization.yaml
  overlays/crc/data-science/kustomization.yaml
  overlays/crc/kustomization.yaml
  overlays/crc/operate-first/argo.yaml
  overlays/crc/operate-first/dashboard.yaml
  overlays/crc/operate-first/datacatalog.yaml
  overlays/crc/operate-first/jupyterhub.yaml
  overlays/crc/operate-first/kustomization.yaml
  overlays/crc/operate-first/monitoring.yaml
  overlays/crc/operate-first/odh-operator.yaml
  overlays/crc/operate-first/superset.yaml
  overlays/crc/thoth/kustomization.yaml
  overlays/moc/data-science/kustomization.yaml
  overlays/moc/kustomization.yaml
  overlays/moc/operate-first/argo.yaml
  overlays/moc/operate-first/dashboard.yaml
  overlays/moc/operate-first/datacatalog.yaml
  overlays/moc/operate-first/jupyterhub.yaml
  overlays/moc/operate-first/kustomization.yaml
  overlays/moc/operate-first/monitoring.yaml
  overlays/moc/operate-first/superset.yaml
  overlays/moc/thoth/kustomization.yaml
  overlays/quicklab/data-science/kustomization.yaml
  overlays/quicklab/kustomization.yaml
  overlays/quicklab/operate-first/argo.yaml
  overlays/quicklab/operate-first/dashboard.yaml
  overlays/quicklab/operate-first/datacatalog.yaml
  overlays/quicklab/operate-first/jupyterhub.yaml
  overlays/quicklab/operate-first/kustomization.yaml
  overlays/quicklab/operate-first/monitoring.yaml
  overlays/quicklab/operate-first/odh-operator.yaml
  overlays/quicklab/operate-first/superset.yaml
  overlays/quicklab/thoth/kustomization.yaml
Labels: approved, size/L

#15 Add Kafka
  base/operate-first/kafka.yaml
  base/operate-first/kustomization.yaml
  overlays/crc/operate-first/kafka.yaml
  overlays/crc/operate-first/kustomization.yaml
  overlays/moc/operate-first/kafka.yaml
  overlays/moc/operate-first/kustomization.yaml
  overlays/quicklab/operate-first/kafka.yaml
  overlays/quicklab/operate-first/kustomization.yaml
Labels: approved, size/M

#19 Update ODH component paths
  base/operate-first/argo.yaml
  base/operate-first/dashboard.yaml
  base/operate-first/datacatalog.yaml
  base/operate-first/jupyterhub.yaml
  base/operate-first/kafka.yaml
  base/operate-first/monitoring.yaml
  base/operate-first/superset.yaml
  overlays/crc/operate-first/argo.yaml
  overlays/crc/operate-first/dashboard.yaml
  overlays/crc/operate-first/datacatalog.yaml
  overlays/crc/operate-first/jupyterhub.yaml
  overlays/crc/operate-first/kafka.yaml
  overlays/crc/operate-first/monitoring.yaml
  overlays/crc/operate-first/odh-operator.yaml
  overlays/crc/operate-first/superset.yaml
  overlays/moc/operate-first/argo.yaml
  overlays/moc/operate-first/dashboard.yaml
  overlays/moc/operate-first/datacatalog.yaml
  overlays/moc/operate-first/jupyterhub.yaml
  overlays/moc/operate-first/kafka.yaml
  overlays/moc/operate-first/monitoring.yaml
  overlays/moc/operate-first/superset.yaml
  overlays/quicklab/operate-first/argo.yaml
  overlays/quicklab/operate-first/dashboard.yaml
  overlays/quicklab/operate-first/datacatalog.yaml
  overlays/quicklab/operate-first/jupyterhub.yaml
  overlays/quicklab/operate-first/kafka.yaml
  overlays/quicklab/operate-first/monitoring.yaml
  overlays/quicklab/operate-first/odh-operator.yaml
  overlays/quicklab/operate-first/superset.yaml
Labels: approved, size/M

#20 support thoth production deployment
  overlays/moc/thoth/kustomization.yaml
  overlays/moc/thoth/prod/core-backend.yaml
  overlays/moc/thoth/prod/core-frontend.yaml
  overlays/moc/thoth/prod/core-graph.yaml
  overlays/moc/thoth/prod/core-infra.yaml
  overlays/moc/thoth/prod/core-middletier.yaml
  overlays/moc/thoth/prod/kustomization.yaml
  overlays/moc/thoth/prod/prod-thoth-advise-reporter.yaml
  overlays/moc/thoth/prod/prod-thoth-adviser.yaml
  overlays/moc/thoth/prod/prod-thoth-amun-api.yaml
  overlays/moc/thoth/prod/prod-thoth-amun-inspection.yaml
  overlays/moc/thoth/prod/prod-thoth-chat-notification.yaml
  overlays/moc/thoth/prod/prod-thoth-cve-update.yaml
  overlays/moc/thoth/prod/prod-thoth-graph-backup.yaml
  overlays/moc/thoth/prod/prod-thoth-graph-refresh.yaml
  overlays/moc/thoth/prod/prod-thoth-graph-sync-backend.yaml
  overlays/moc/thoth/prod/prod-thoth-graph-sync-middletier.yaml
  overlays/moc/thoth/prod/prod-thoth-investigator.yaml
  overlays/moc/thoth/prod/prod-thoth-kebechet.yaml
  overlays/moc/thoth/prod/prod-thoth-management-api.yaml
  overlays/moc/thoth/prod/prod-thoth-metrics-exporter.yaml
  overlays/moc/thoth/prod/prod-thoth-mi.yaml
  overlays/moc/thoth/prod/prod-thoth-package-extract.yaml
  overlays/moc/thoth/prod/prod-thoth-package-releases.yaml
  overlays/moc/thoth/prod/prod-thoth-package-update.yaml
  overlays/moc/thoth/prod/prod-thoth-qeb-hwt.yaml
  overlays/moc/thoth/prod/prod-thoth-revsolver.yaml
  overlays/moc/thoth/prod/prod-thoth-security-indicators.yaml
  overlays/moc/thoth/prod/prod-thoth-slo-reporter.yaml
  overlays/moc/thoth/prod/prod-thoth-solver.yaml
  overlays/moc/thoth/prod/prod-thoth-user-api.yaml
Labels: approved, size/XL

#21 patch server url for thoth deployments
  overlays/moc/thoth/prod/core-backend.yaml
  overlays/moc/thoth/prod/core-frontend.yaml
  overlays/moc/thoth/prod/core-graph.yaml
  overlays/moc/thoth/prod/core-infra.yaml
  overlays/moc/thoth/prod/core-middletier.yaml
  overlays/moc/thoth/prod/prod-thoth-advise-reporter.yaml
  overlays/moc/thoth/prod/prod-thoth-adviser.yaml
  overlays/moc/thoth/prod/prod-thoth-amun-api.yaml
  overlays/moc/thoth/prod/prod-thoth-amun-inspection.yaml
  overlays/moc/thoth/prod/prod-thoth-chat-notification.yaml
  overlays/moc/thoth/prod/prod-thoth-cve-update.yaml
  overlays/moc/thoth/prod/prod-thoth-graph-backup.yaml
  overlays/moc/thoth/prod/prod-thoth-graph-refresh.yaml
  overlays/moc/thoth/prod/prod-thoth-graph-sync-backend.yaml
  overlays/moc/thoth/prod/prod-thoth-graph-sync-middletier.yaml
  overlays/moc/thoth/prod/prod-thoth-investigator.yaml
  overlays/moc/thoth/prod/prod-thoth-kebechet.yaml
  overlays/moc/thoth/prod/prod-thoth-management-api.yaml
  overlays/moc/thoth/prod/prod-thoth-metrics-exporter.yaml
  overlays/moc/thoth/prod/prod-thoth-mi.yaml
  overlays/moc/thoth/prod/prod-thoth-package-extract.yaml
  overlays/moc/thoth/prod/prod-thoth-package-releases.yaml
  overlays/moc/thoth/prod/prod-thoth-package-update.yaml
  overlays/moc/thoth/prod/prod-thoth-qeb-hwt.yaml
  overlays/moc/thoth/prod/prod-thoth-revsolver.yaml
  overlays/moc/thoth/prod/prod-thoth-security-indicators.yaml
  overlays/moc/thoth/prod/prod-thoth-slo-reporter.yaml
  overlays/moc/thoth/prod/prod-thoth-solver.yaml
  overlays/moc/thoth/prod/prod-thoth-user-api.yaml
Labels: approved, size/M

#24 added sefkhet-abwy-chatbot application
  overlays/moc/thoth/prod/kustomization.yaml
  overlays/moc/thoth/prod/prod-thoth-bot-sefkhet-abwy-chatbot.yaml
Labels: approved, size/S

#26 Remove unnecessary root kustomization for moc
  kustomization.yaml
Labels: approved, size/XS
