Repository operate-first/argocd-apps, pull requests merged in 2021-06, with the labels that each got.

#148 service-registry, changed base folder
  envs/moc/zero/apicurio/registry.yml
Labels: approved, lgtm, ok-to-test, size/XS

#150 remove ipolonsk from owners
  OWNERS
Labels: approved, lgtm, size/XS

#151 chore: Set opf-toolbox to latest in Prow
  .prow.yaml
Labels: approved, lgtm, size/XS

#152 update the thoth mi app deployment
  envs/moc/zero/thoth/prod/prod-thoth-mi.yaml
  envs/moc/zero/thoth/test/test-thoth-mi.yaml
Labels: approved, lgtm, size/XS

#153 deploy triage-party #1649 ArgoCD Deployment Manifests
  envs/moc/zero/thoth/prod/kustomization.yaml
  envs/moc/zero/thoth/prod/prod-thoth-triage-party.yaml
Labels: approved, lgtm, size/S

#154 remove the prescription sync job as it is deprecated
  envs/moc/zero/thoth/prod/kustomization.yaml
  envs/moc/zero/thoth/prod/prod-thoth-prescription-sync.yaml
  envs/moc/zero/thoth/test/kustomization.yaml
  envs/moc/zero/thoth/test/test-thoth-prescription-sync.yaml
Labels: approved, lgtm, size/M

#155 setup the investigator message metrics for prod
  envs/moc/zero/thoth/prod/kustomization.yaml
  envs/moc/zero/thoth/prod/prod-thoth-investigator-message-metrics.yaml
Labels: approved, lgtm, size/S

#156 INtroduce thoth graph-metrics-exporter component
  envs/moc/zero/thoth/prod/kustomization.yaml
  envs/moc/zero/thoth/prod/prod-thoth-graph-metrics-exporter.yaml
Labels: approved, lgtm, size/S

#159 feat: Enable opendatahub-operator autosync
  envs/moc/zero/operate-first/odh-operator.yaml
Labels: approved, lgtm, size/XS

#160 fix: Don't sync acme operator configmap
  envs/moc/zero/operate-first/acme-operator.yaml
Labels: approved, lgtm, size/XS

#162 enable argocd support for the prescriptions-gh-release-notes
  envs/moc/zero/thoth/prod/kustomization.yaml
  envs/moc/zero/thoth/prod/prod-thoth-prescriptions-gh-release-notes.yaml
Labels: approved, lgtm, size/S

#158 updated graph-backup to graph namespace
  envs/moc/zero/thoth/prod/prod-thoth-graph-backup.yaml
Labels: approved, lgtm, size/XS

#168 change the deployment namespace for thoth task graph
  envs/moc/zero/thoth/prod/prod-thoth-purge-job.yaml
Labels: approved, lgtm, size/XS

#166 enable argocd to support thoth graph update schema deploy
  envs/moc/zero/thoth/prod/kustomization.yaml
  envs/moc/zero/thoth/prod/prod-thoth-graph-schema-update.yaml
Labels: approved, lgtm, size/S

#167 Deprecate qebhwt application from thoth-services
  envs/moc/zero/thoth/prod/kustomization.yaml
  envs/moc/zero/thoth/prod/prod-thoth-qeb-hwt.yaml
Labels: approved, lgtm, size/S

#163 feat: Move cluster scope overlays around for multi geo
  envs/moc/curator/cluster-management/cluster-resources.yaml
  envs/moc/infra/cluster-management/cluster-resources.yaml
  envs/moc/zero/cluster-management/cluster-resources.yaml
Labels: approved, lgtm, size/XS

#169 Fix path for cluster-resources.
  envs/moc/curator/cluster-management/cluster-resources.yaml
  envs/moc/infra/cluster-management/cluster-resources.yaml
  envs/moc/zero/cluster-management/cluster-resources.yaml
Labels: approved, lgtm, size/XS
