Repository operate-first/argocd-apps, pull requests merged in 2021-08, with the labels that each got.

#171 feat: add Rick apps
  app-of-apps/app-of-apps-rick.yaml
  app-of-apps/kustomization.yaml
  envs/emea/rick/cluster-management/alertreceiver.yaml
  envs/emea/rick/cluster-management/cluster-resources.yaml
  envs/emea/rick/cluster-management/kustomization.yaml
  envs/emea/rick/cluster-management/local-storage.yaml
  envs/emea/rick/kustomization.yaml
Labels: approved, lgtm, size/L

#173 deprecated the prescriptions gh release notes job
  envs/moc/zero/thoth/prod/kustomization.yaml
  envs/moc/zero/thoth/prod/prod-thoth-prescriptions-gh-release-notes.yaml
Labels: approved, lgtm

#184 feat: Onboard DevConf.US 2021 cluster
  app-of-apps/app-of-apps-devconfus2021.yaml
  envs/emea/devconfus2021/cluster-management/cluster-resources.yaml
  envs/emea/devconfus2021/cluster-management/kfdefs.yaml
  envs/emea/devconfus2021/cluster-management/kustomization.yaml
  envs/emea/devconfus2021/kustomization.yaml
  envs/emea/devconfus2021/operate-first/kubeflow.yaml
  envs/emea/devconfus2021/operate-first/kustomization.yaml
  envs/emea/devconfus2021/operate-first/odh-operator.yaml
Labels: approved, size/L

#185 fix: DevconfUS cluster was not allowed for operate-first project
  projects/operate-first.yaml
Labels: size/XS, lgtm

#188 fix: app-of-apps missing resources + proper workshop path
  app-of-apps/kustomization.yaml
  app-of-apps/workshops-app-of-apps.yaml
  app-of-apps/workshops/kustomization.yaml
  app-of-apps/workshops/lab-cicd-app-of-apps.yaml
Labels: size/M, approved, lgtm

#189 fix: ApplicationSets should be allowed in operate first ArgoCD project
  projects/operate-first.yaml
Labels: size/XS, lgtm

#190 Revert "fix: ApplicationSets should be allowed in operate first ArgoCD project"
  projects/operate-first.yaml
Labels: size/XS, lgtm
