Repository operate-first/argocd-apps, pull requests merged in 2021-03, with the labels that each got.

#88 Improve adding application docs
  docs/add_application.md
  docs/add_permissions_to_project.md
Labels: approved, lgtm, size/M

#89 chore: Update test-kustomize-build in .prow.yaml
  .aicoe-ci.yaml
  .prow.yaml
Labels: approved, lgtm, size/XS

#91 Updated docs to reflect new dir structure.
  docs/add_application.md
  scripts/create-project.sh
Labels: approved, lgtm, size/M

#93 Add kubevirt app for infra
  envs/moc/infra/cluster-management/kubevirt-hyperconverged.yaml
  envs/moc/infra/cluster-management/kustomization.yaml
Labels: size/S

#95 Make name unique
  envs/moc/infra/cluster-management/kubevirt-hyperconverged.yaml
Labels: size/XS

#92 Update cluster name
  docs/add_application.md
  envs/moc/zero/cluster-management/ceph.yaml
  envs/moc/zero/cluster-management/cluster-resources.yaml
  envs/moc/zero/cluster-management/kubevirt-hyperconverged.yaml
  envs/moc/zero/cluster-management/local-storage.yaml
  envs/moc/zero/data-science/black-flake.yml
  envs/moc/zero/data-science/mailing-list-analysis-toolkit.yaml
  envs/moc/zero/operate-first/argo.yaml
  envs/moc/zero/operate-first/ci-prow.yaml
  envs/moc/zero/operate-first/cluster-logging.yaml
  envs/moc/zero/operate-first/dashboard.yaml
  envs/moc/zero/operate-first/datacatalog.yaml
  envs/moc/zero/operate-first/jupyterhub.yaml
  envs/moc/zero/operate-first/kafka.yaml
  envs/moc/zero/operate-first/monitoring.yaml
  envs/moc/zero/operate-first/observatorium.yaml
  envs/moc/zero/operate-first/prod-aicoe-ci.yaml
  envs/moc/zero/operate-first/superset.yaml
  envs/moc/zero/thoth/prod/core-backend.yaml
  envs/moc/zero/thoth/prod/core-frontend.yaml
  envs/moc/zero/thoth/prod/core-graph.yaml
  envs/moc/zero/thoth/prod/core-infra.yaml
  envs/moc/zero/thoth/prod/core-middletier.yaml
  envs/moc/zero/thoth/prod/prod-thoth-advise-reporter.yaml
  envs/moc/zero/thoth/prod/prod-thoth-adviser.yaml
  envs/moc/zero/thoth/prod/prod-thoth-amun-api.yaml
  envs/moc/zero/thoth/prod/prod-thoth-amun-inspection.yaml
  envs/moc/zero/thoth/prod/prod-thoth-bot-sefkhet-abwy-chatbot.yaml
  envs/moc/zero/thoth/prod/prod-thoth-chat-notification.yaml
  envs/moc/zero/thoth/prod/prod-thoth-cve-update.yaml
  envs/moc/zero/thoth/prod/prod-thoth-elyra-aidevsecops-tutorial.yaml
  envs/moc/zero/thoth/prod/prod-thoth-graph-backup.yaml
  envs/moc/zero/thoth/prod/prod-thoth-graph-refresh.yaml
  envs/moc/zero/thoth/prod/prod-thoth-graph-sync-backend.yaml
  envs/moc/zero/thoth/prod/prod-thoth-graph-sync-middletier.yaml
  envs/moc/zero/thoth/prod/prod-thoth-investigator.yaml
  envs/moc/zero/thoth/prod/prod-thoth-kebechet.yaml
  envs/moc/zero/thoth/prod/prod-thoth-management-api.yaml
  envs/moc/zero/thoth/prod/prod-thoth-metrics-exporter.yaml
  envs/moc/zero/thoth/prod/prod-thoth-mi.yaml
  envs/moc/zero/thoth/prod/prod-thoth-package-extract.yaml
  envs/moc/zero/thoth/prod/prod-thoth-package-releases.yaml
  envs/moc/zero/thoth/prod/prod-thoth-package-update.yaml
  envs/moc/zero/thoth/prod/prod-thoth-qeb-hwt.yaml
  envs/moc/zero/thoth/prod/prod-thoth-revsolver.yaml
  envs/moc/zero/thoth/prod/prod-thoth-security-indicators.yaml
  envs/moc/zero/thoth/prod/prod-thoth-sefkhet-abwy.yaml
  envs/moc/zero/thoth/prod/prod-thoth-slo-reporter.yaml
  envs/moc/zero/thoth/prod/prod-thoth-solver.yaml
  envs/moc/zero/thoth/prod/prod-thoth-user-api.yaml
Labels: do-not-merge/hold, lgtm, size/L

#98 Add observatorium-operator to operate-first kustomization
  envs/moc/zero/operate-first/kustomization.yaml
Labels: approved, lgtm, size/XS

#99 migrate slo reporter to the stage environment
  envs/moc/zero/thoth/prod/kustomization.yaml
  envs/moc/zero/thoth/prod/prod-thoth-slo-reporter.yaml
Labels: approved, lgtm, size/S

#100 feat: Add apps for GH alert receiver
  .aicoe-ci.yaml
  envs/moc/infra/cluster-management/alertreceiver.yaml
  envs/moc/infra/cluster-management/kustomization.yaml
  envs/moc/zero/cluster-management/alertreceiver.yaml
  envs/moc/zero/cluster-management/kustomization.yaml
Labels: approved, lgtm, size/M

#102 fix: Alert receiver on zero destination
  envs/moc/zero/cluster-management/alertreceiver.yaml
Labels: approved, size/XS

#104 feat: Add auth app
  envs/moc/zero/operate-first/auth.yaml
  envs/moc/zero/operate-first/kustomization.yaml
Labels: approved, lgtm, size/S

#105 Add odh-operator app
  envs/moc/zero/operate-first/kustomization.yaml
  envs/moc/zero/operate-first/odh-operator.yaml
Labels: approved, lgtm, size/S

#107 Sync apps with live state.
  envs/moc/zero/data-science/black-flake.yml
  envs/moc/zero/data-science/mailing-list-analysis-toolkit.yaml
Labels: approved, size/XS

#109 Update ns path
  envs/moc/zero/operate-first/odh-operator.yaml
Labels: approved, size/XS

#106 Add kfdef app.
  envs/moc/zero/operate-first/kfdefs.yaml
  envs/moc/zero/operate-first/kustomization.yaml
Labels: approved, lgtm, size/S

#112 chore: Remove naved001 from OWNERS
  OWNERS
Labels: approved, size/XS

#113 Move kfdef app to be under cluster-management proj.
  envs/moc/zero/cluster-management/kfdefs.yaml
  envs/moc/zero/cluster-management/kustomization.yaml
  envs/moc/zero/operate-first/kustomization.yaml
Labels: approved, lgtm, size/XS

#111 feat: Add knative app
  envs/moc/zero/cluster-management/knative.yaml
  envs/moc/zero/cluster-management/kustomization.yaml
Labels: approved, size/S

#101 chore: Cleanup ArgoCD app names
  envs/moc/infra/cluster-management/alertreceiver.yaml
  envs/moc/infra/cluster-management/cluster-resources.yaml
  envs/moc/infra/cluster-management/kubevirt-hyperconverged.yaml
  envs/moc/infra/cluster-management/kustomization.yaml
  envs/moc/zero/cluster-management/alertreceiver.yaml
  envs/moc/zero/cluster-management/kustomization.yaml
Labels: approved, size/S

#114 add metallb to zero cluster
  envs/moc/zero/cluster-management/kustomization.yaml
  envs/moc/zero/cluster-management/metallb.yaml
Labels: approved, do-not-merge/hold, size/S

#116 Onboard curator cluster
  envs/moc/curator/cluster-management/cluster-resources.yaml
  envs/moc/curator/cluster-management/kustomization.yaml
  envs/moc/curator/kustomization.yaml
Labels: approved, lgtm, size/M

#117 Add staging JH app
  envs/moc/zero/operate-first/jupyterhub-stage.yaml
  envs/moc/zero/operate-first/kustomization.yaml
Labels: approved, size/S

#118 Change default cluster-resources ns to guaranteed existing ns.
  envs/moc/curator/cluster-management/cluster-resources.yaml
  envs/moc/infra/cluster-management/cluster-resources.yaml
  envs/moc/zero/cluster-management/cluster-resources.yaml
Labels: approved, lgtm, size/XS

#110 support thoth-prescription job with the argocd
  envs/moc/zero/thoth/prod/kustomization.yaml
  envs/moc/zero/thoth/prod/prod-thoth-prescription-sync.yaml
Labels: approved, lgtm, size/S

#119 Relocate per-cluster app-of-apps to argocd-apps
  app-of-apps/app-of-apps-curator.yaml
  app-of-apps/app-of-apps-infra.yaml
  app-of-apps/app-of-apps-zero.yaml
  app-of-apps/kustomization.yaml
Labels: approved, lgtm, size/M

#120 feat: Add application for opf-ci-test-pods namespace
  envs/moc/zero/operate-first/ci-prow-test-pods.yaml
  envs/moc/zero/operate-first/kustomization.yaml
Labels: approved, lgtm, size/M

#121 add b4mad app / minecraft
  envs/moc/zero/b4mad/kustomization.yaml
  envs/moc/zero/b4mad/minecraft.yml
  envs/moc/zero/kustomization.yaml
Labels: approved, size/S

#123 Turn off autosync for ml app of apps.
  envs/moc/infra/workshops/app-of-apps.yaml
Labels: approved, size/XS

#122 feat: Add lab-cicd app of apps and relocate workshop app of apps
  app-of-apps/kustomization.yaml
  app-of-apps/workshops/kustomization.yaml
  app-of-apps/workshops/lab-cicd-app-of-apps.yaml
  app-of-apps/workshops/ml-prague-app-of-apps.yaml
  envs/moc/infra/kustomization.yaml
Labels: approved, lgtm, size/S

#125 chore(prow): Lower CPU request
  .prow.yaml
Labels: approved, lgtm, size/XS

#124 Update paths pointing to cd repo to point to apps instead.
  docs/add_application.md
  docs/add_permissions_to_project.md
  envs/moc/infra/cluster-management/argocd-projects.yaml
Labels: approved, lgtm, size/M
