Repository operate-first/argocd-apps, pull requests merged in 2021-01, with the labels that each got.

#28 Update moc github links in docs, and clear up instructions.
  docs/onboard_team_to_argocd.md
Labels: approved, do-not-merge/hold, size/M

#29 Add docs for requesting additional permissions
  docs/add_permissions_to_project.md
Labels: approved, size/S

#25 Add Observatorium App
  base/operate-first/kustomization.yaml
  base/operate-first/observatorium.yaml
  overlays/crc/operate-first/observatorium.yaml
  overlays/moc/operate-first/observatorium.yaml
  overlays/quicklab/operate-first/observatorium.yaml
Labels: approved, size/M

#32 Enable autosync for all odh apps
  base/operate-first/argo.yaml
  base/operate-first/dashboard.yaml
  base/operate-first/datacatalog.yaml
  base/operate-first/jupyterhub.yaml
  base/operate-first/kafka.yaml
  base/operate-first/monitoring.yaml
  base/operate-first/superset.yaml
Labels: approved, size/S

#35 Add observatorium to overlay kustomizations
  overlays/crc/operate-first/kustomization.yaml
  overlays/moc/operate-first/kustomization.yaml
  overlays/quicklab/operate-first/kustomization.yaml
Labels: approved, size/XS

#38 Create OWNERS
  overlays/moc/thoth/OWNERS
Labels: approved, do-not-merge/invalid-owners-file, size/S

#39 Update Readme with console link.
  README.md
Labels: approved, size/XS

#41 opf-ci-prow component is deployed on moc cluster only
  overlays/moc/operate-first/kustomization.yaml
Labels: approved, bug, kind/bug, priority/important-soon

#36 Add cluster group management app
  base/cluster-management/cluster-resources.yaml
  base/cluster-management/kustomization.yaml
  docs/onboard_team_to_argocd.md
  overlays/crc/cluster-management/cluster-resources.yaml
  overlays/crc/cluster-management/kustomization.yaml
  overlays/crc/kustomization.yaml
  overlays/moc/cluster-management/argocd-projects.yaml
  overlays/moc/cluster-management/cluster-resources.yaml
  overlays/moc/cluster-management/kustomization.yaml
  overlays/moc/kustomization.yaml
  overlays/quicklab/cluster-management/cluster-resources.yaml
  overlays/quicklab/cluster-management/kustomization.yaml
  overlays/quicklab/kustomization.yaml
Labels: approved, size/L

#45 Fix kustomization resource
  overlays/moc/cluster-management/kustomization.yaml
Labels: approved, size/XS

#46 Fix cluster name in cluster-management group
  base/cluster-management/cluster-resources.yaml
Labels: approved, size/XS

#44 moving cluster stuff to the right place
  overlays/moc/operate-first/ci-prow.yaml
Labels: approved, kind/feature, sig/devops, size/S

#47 Enable auto sync policy for cluster resources
  base/cluster-management/cluster-resources.yaml
Labels: approved, size/XS

#40 Onboard mesh-for-data
  base/mesh-for-data/kustomization.yaml
  overlays/crc/kustomization.yaml
  overlays/crc/mesh-for-data/kustomization.yaml
  overlays/moc/kustomization.yaml
  overlays/moc/mesh-for-data/kustomization.yaml
  overlays/quicklab/kustomization.yaml
  overlays/quicklab/mesh-for-data/kustomization.yaml
Labels: approved, size/S

#49 Ignore image fields for prow app
  overlays/moc/operate-first/ci-prow.yaml
Labels: approved, size/XS

#50 Ignore image field in amun inspection app
  overlays/moc/thoth/prod/prod-thoth-amun-inspection.yaml
Labels: approved, size/XS

#51 Add Elyra AIDevSecOps Tutorial
  overlays/moc/thoth/prod/kustomization.yaml
  overlays/moc/thoth/prod/prod-thoth-elyra-aidevsecops-tutorial.yaml
Labels: approved, size/S

#52 support sefkhet-abwy application with argocd
  overlays/moc/thoth/prod/kustomization.yaml
  overlays/moc/thoth/prod/prod-thoth-sefkhet-abwy.yaml
Labels: approved, size/S

#53 fix the manifest path of the thoth-elyra-aidevsecops
  overlays/moc/thoth/prod/prod-thoth-elyra-aidevsecops-tutorial.yaml
Labels: approved, size/XS

#54 ignore difference of image in sefkhet-abwy cronjob
  overlays/moc/thoth/prod/prod-thoth-sefkhet-abwy.yaml
Labels: approved, size/S

#55 fix the path used for ignoring difference of image
  overlays/moc/thoth/prod/prod-thoth-sefkhet-abwy.yaml
Labels: approved, size/XS

#56 ignore difference of image for ghproxy deployment
  overlays/moc/thoth/prod/prod-thoth-sefkhet-abwy.yaml
Labels: approved, size/XS

#58 feat: Create a standalone ClusterLogging app within operate-first project
  base/operate-first/cluster-logging.yaml
  base/operate-first/kustomization.yaml
  overlays/crc/operate-first/cluster-logging.yaml
  overlays/crc/operate-first/kustomization.yaml
  overlays/moc/operate-first/cluster-logging.yaml
  overlays/moc/operate-first/kustomization.yaml
  overlays/quicklab/operate-first/cluster-logging.yaml
  overlays/quicklab/operate-first/kustomization.yaml
Labels: approved, do-not-merge/hold, size/M

#59 Add SLO reporter to kustomize
  overlays/moc/thoth/prod/kustomization.yaml
Labels: approved, size/XS
