Repository operate-first/argocd-apps, pull requests merged in 2021-09, with the labels that each got.

#186 feat: move ci-prow to smaug
  envs/moc/smaug/operate-first/ci-prow-test-pods.yaml
  envs/moc/smaug/operate-first/ci-prow.yaml
  envs/moc/smaug/operate-first/kustomization.yaml
Labels: size/M

#195 Prune the thoth-station Test from the zero cluster
  envs/moc/zero/thoth/test/kustomization.yaml
Labels: approved, size/S, lgtm

#194 Prune the ci prow from the zero cluster
  envs/moc/zero/operate-first/kustomization.yaml
Labels: approved, lgtm

#197 feat: migrate the aicoe-ci to smaug cluster
  envs/moc/smaug/operate-first/kustomization.yaml
  envs/moc/smaug/operate-first/prod-aicoe-ci.yaml
Labels: lgtm

#196 Remove ocp-prod apps from this repository
  app-of-apps/app-of-apps-ocp-prod.yaml
  envs/moc/ocp-prod/cluster-management/cluster-resources.yaml
  envs/moc/ocp-prod/cluster-management/kustomization.yaml
  envs/moc/ocp-prod/external-secrets/external-secrets.yaml
  envs/moc/ocp-prod/external-secrets/kustomization.yaml
  envs/moc/ocp-prod/kustomization.yaml
  projects/global_project.yaml
  projects/mocops.yaml
Labels: size/M

#199 Remove devconf2021 apps.
  app-of-apps/app-of-apps-devconfus2021.yaml
  app-of-apps/kustomization.yaml
  envs/emea/devconfus2021/cluster-management/cluster-resources.yaml
  envs/emea/devconfus2021/cluster-management/kfdefs.yaml
  envs/emea/devconfus2021/cluster-management/kustomization.yaml
  envs/emea/devconfus2021/kustomization.yaml
  envs/emea/devconfus2021/operate-first/grafana.yaml
  envs/emea/devconfus2021/operate-first/kubeflow.yaml
  envs/emea/devconfus2021/operate-first/kustomization.yaml
  envs/emea/devconfus2021/operate-first/odh-operator.yaml
Labels: approved, size/L, lgtm

#200 Add dex app for smaug cluster
  envs/moc/smaug/cluster-management/dex.yaml
  envs/moc/smaug/cluster-management/kustomization.yaml
Labels: approved, size/S, lgtm

#201 Permit mocops project access to CCI-MOC repos via ssh
  projects/mocops.yaml
Labels: approved, size/XS, lgtm

#203 Use ssh:// urls instead of user@host:/path urls
  projects/mocops.yaml
Labels: size/XS

#207 Enable democratic csi on smaug cluster
  envs/moc/smaug/cluster-management/kustomization.yaml
  envs/moc/smaug/cluster-management/moc-nfs-democratic-csi.yaml
Labels: approved, size/S, lgtm

#206 Remove deprecated apps from the service
  envs/moc/zero/operate-first/ci-prow-test-pods.yaml
  envs/moc/zero/operate-first/ci-prow.yaml
  envs/moc/zero/operate-first/kustomization.yaml
Labels: size/M, approved, lgtm

#209 Update thoth.yaml
  projects/thoth.yaml
Labels: approved, size/XS, lgtm

#187 feat: move slack-first to smaug
  envs/moc/smaug/operate-first/kustomization.yaml
  envs/moc/smaug/operate-first/slack-first.yaml
  envs/moc/zero/operate-first/kustomization.yaml
Labels: approved, size/XS, lgtm

#208 Creating ArgoCD Project and app for Fybrik
  envs/moc/smaug/fybrik/kustomization.yaml
  projects/fybrik.yaml
  projects/mesh-for-data.yaml
Labels: size/M, approved, lgtm, ok-to-test

#204 Move the thoth-station test apps to rick
  envs/emea/rick/kustomization.yaml
  envs/emea/rick/thoth/OWNERS
  envs/emea/rick/thoth/kustomization.yaml
  envs/emea/rick/thoth/test/core-test.yaml
  envs/emea/rick/thoth/test/kustomization.yaml
  envs/emea/rick/thoth/test/test-thoth-advise-reporter.yaml
  envs/emea/rick/thoth/test/test-thoth-adviser.yaml
  envs/emea/rick/thoth/test/test-thoth-amun-api.yaml
  envs/emea/rick/thoth/test/test-thoth-chat-notification.yaml
  envs/emea/rick/thoth/test/test-thoth-cve-update.yaml
  envs/emea/rick/thoth/test/test-thoth-graph-backup.yaml
  envs/emea/rick/thoth/test/test-thoth-graph-refresh.yaml
  envs/emea/rick/thoth/test/test-thoth-graph-sync.yaml
  envs/emea/rick/thoth/test/test-thoth-investigator.yaml
  envs/emea/rick/thoth/test/test-thoth-kebechet.yaml
  envs/emea/rick/thoth/test/test-thoth-management-api.yaml
  envs/emea/rick/thoth/test/test-thoth-metrics-exporter.yaml
  envs/emea/rick/thoth/test/test-thoth-mi.yaml
  envs/emea/rick/thoth/test/test-thoth-package-extract.yaml
  envs/emea/rick/thoth/test/test-thoth-package-releases.yaml
  envs/emea/rick/thoth/test/test-thoth-package-update.yaml
  envs/emea/rick/thoth/test/test-thoth-revsolver.yaml
  envs/emea/rick/thoth/test/test-thoth-security-indicators.yaml
  envs/emea/rick/thoth/test/test-thoth-solver.yaml
  envs/emea/rick/thoth/test/test-thoth-user-api.yaml
  envs/moc/zero/thoth/kustomization.yaml
Labels: size/M, approved, lgtm

#213 add argocd app to deploy acme-operator on rick
  envs/emea/rick/kustomization.yaml
  envs/emea/rick/operate-first/acme-operator.yaml
  envs/emea/rick/operate-first/kustomization.yaml
  projects/operate-first.yaml
Labels: size/M, approved, lgtm

#214 Remove m4d from kustomization.
  projects/kustomization.yaml
Labels: approved, size/XS

#215 Remove trailing slash for rick cluster in op1st proj.
  projects/operate-first.yaml
Labels: size/XS, lgtm

#212 feat: Add cert-manager app
  envs/moc/smaug/cluster-management/cert-manager.yaml
  envs/moc/smaug/cluster-management/kustomization.yaml
Labels: approved, size/S, lgtm

#217 setup an kafka app for rick cluster
  envs/emea/rick/operate-first/kustomization.yaml
  envs/emea/rick/operate-first/opf-kafka.yaml
Labels: approved, size/S, lgtm

#218 Add acme/cluster-resources to balrog.
  app-of-apps/app-of-apps-balrog.yaml
  app-of-apps/kustomization.yaml
  envs/emea/balrog/cluster-management/cluster-resources.yaml
  envs/emea/balrog/cluster-management/kustomization.yaml
  envs/emea/balrog/kustomization.yaml
  envs/emea/balrog/operate-first/acme-operator.yaml
  envs/emea/balrog/operate-first/kustomization.yaml
  projects/operate-first.yaml
  projects/thoth.yaml
Labels: approved, size/L, lgtm

#219 Enable node-labeler app
  envs/moc/smaug/cluster-management/kustomization.yaml
  envs/moc/smaug/cluster-management/node-labeler.yaml
Labels: approved, size/S, lgtm

#220 Add kfdefs app to moc/smaug env
  envs/moc/smaug/cluster-management/kfdefs.yaml
  envs/moc/smaug/cluster-management/kustomization.yaml
Labels: approved, size/S, lgtm

#211 feat: add grafana to smaug cluster
  envs/moc/smaug/operate-first/grafana.yaml
  envs/moc/smaug/operate-first/kustomization.yaml
Labels: approved, size/S, lgtm

#221 Remove applications from kustomization.
  envs/moc/smaug/cluster-management/kustomization.yaml
  envs/moc/smaug/operate-first/kustomization.yaml
Labels: approved, size/XS, lgtm
