Repository operate-first/argocd-apps, pull requests merged in 2021-02, with the labels that each got.

#57 deploy aicoe-ci component via argo cd
  base/operate-first/ci-prow.yaml
  base/operate-first/kustomization.yaml
  base/operate-first/prod-aicoe-ci.yaml
  overlays/moc/operate-first/kustomization.yaml
  overlays/moc/operate-first/prod-aicoe-ci.yaml
Labels: approved, lgtm, size/M

#61 Update owners file.
  OWNERS
Labels: approved, size/S

#60 feat: Add standalone apps for operator resources
  base/cluster-management/ceph.yaml
  base/cluster-management/kubevirt-hyperconverged.yaml
  base/cluster-management/kustomization.yaml
  base/cluster-management/local-storage.yaml
  overlays/moc/cluster-management/ceph.yaml
  overlays/moc/cluster-management/kubevirt-hyperconverged.yaml
  overlays/moc/cluster-management/kustomization.yaml
  overlays/moc/cluster-management/local-storage.yaml
Labels: approved, lgtm, size/M

#62 Add black flake app.
  overlays/moc/data-science/black-flake.yml
  overlays/moc/data-science/kustomization.yaml
Labels: approved, size/S

#64 feat: Create workshops app of apps
  base/workshops/app-of-apps.yaml
  base/workshops/kustomization.yaml
  overlays/moc/kustomization.yaml
  overlays/moc/workshops/kustomization.yaml
Labels: approved, size/M

#66 fix: Workshops app project
  base/workshops/app-of-apps.yaml
Labels: approved, size/XS

#68 feat: ODH operator was moved to cluster-resources, removing app
  overlays/crc/operate-first/kustomization.yaml
  overlays/crc/operate-first/odh-operator.yaml
  overlays/quicklab/operate-first/kustomization.yaml
  overlays/quicklab/operate-first/odh-operator.yaml
Labels: approved, lgtm, size/M

#69 ignore image difference for stage thoth slo-reporter
  overlays/moc/thoth/prod/prod-thoth-slo-reporter.yaml
Labels: approved, size/XS

#48 feat: Add Mailing list analysis toolkit
  base/data-science/kustomization.yaml
  base/data-science/mailing-list-analysis-toolkit.yaml
Labels: approved, lgtm, size/S

#70 Turn on thoth components in moc cluster
  overlays/moc/thoth/prod/kustomization.yaml
Labels: approved, lgtm, size/XS

#71 Ignore cluster auth generated values.
  overlays/moc/cluster-management/cluster-resources.yaml
Labels: approved, size/S

#75 Update path for argocd projects in infra.
  overlays/moc-infra/cluster-management/argocd-projects.yaml
Labels: approved, lgtm, size/XS

#77 Fix server destinations for workshop and argocd proj
  overlays/moc-infra/cluster-management/argocd-projects.yaml
  overlays/moc-infra/workshops/app-of-apps.yaml
  overlays/moc-infra/workshops/kustomization.yaml
Labels: approved, lgtm, size/S

#78 Remove workshop from kustomization for cnv.
  overlays/moc-cnv/kustomization.yaml
Labels: approved, lgtm, size/XS

#79 Add workshops app to infra
  overlays/moc-infra/kustomization.yaml
Labels: approved, lgtm, size/XS

#80 Switch workshop cluster to named in-cluster, for patching.
  base/workshops/app-of-apps.yaml
Labels: approved, lgtm, size/XS

#81 Remove version from ignoredifferences for cluster resources.
  overlays/moc-cnv/cluster-management/cluster-resources.yaml
Labels: approved, lgtm, size/XS

#76 add Prow job to inrepoconfig
  .prow.yaml
Labels: approved, lgtm, size/M

#82 Update ArgoCD link
  README.md
Labels: approved, lgtm, size/XS

#84 ignore image difference for thoth graph-refresh cronjob
  .prow.yaml
  overlays/moc-cnv/thoth/prod/prod-thoth-graph-refresh.yaml
Labels: approved, lgtm, sig/devops, size/XS

#83 Update argocd proj path for infra.
  overlays/moc-infra/cluster-management/argocd-projects.yaml
Labels: approved, lgtm, size/XS

#85 feat: Create a standalone ACM app
  overlays/moc-infra/cluster-management/acm.yaml
  overlays/moc-infra/cluster-management/kustomization.yaml
Labels: approved, lgtm, size/S

#86 Enable auto sync for infra cluster app
  overlays/moc-infra/cluster-management/cluster-resources.yaml
Labels: approved, lgtm, size/XS

#87 ignore image difference for ci prow cronjob
  overlays/moc-cnv/operate-first/ci-prow.yaml
Labels: approved, lgtm, size/XS
