Repository operate-first/argocd-apps, pull requests merged in 2021-05, with the labels that each got.

#132 chore: Remove martin from reviewers so he's not flooded by notifications
  OWNERS
Labels: approved, lgtm, size/XS

#133 Add vector app to zero cluster.
  envs/moc/zero/operate-first/kustomization.yaml
  envs/moc/zero/operate-first/vector.yaml
Labels: approved, lgtm, size/S

#134 Apicurio, updated repo configuration
  envs/moc/zero/apicurio/registry.yml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#136 enable the purge job to be deployed
  envs/moc/zero/thoth/prod/kustomization.yaml
  envs/moc/zero/thoth/prod/prod-thoth-purge-job.yaml
Labels: approved, lgtm, size/S

#135 enable moc-nfs-democratic-csi on zero cluster
  envs/moc/zero/cluster-management/kustomization.yaml
  envs/moc/zero/cluster-management/moc-nfs-democratic-csi.yaml
Labels: approved, lgtm, size/S

#139 enable Thoth revsolver in prod
  envs/moc/zero/thoth/prod/kustomization.yaml
Labels: approved, lgtm, size/XS

#140 chore: Disable autosync for Observatorium apps
  envs/moc/zero/operate-first/observatorium-operator.yaml
  envs/moc/zero/operate-first/observatorium.yaml
Labels: approved, lgtm, size/XS

#138 Enable applyoutofsynconly for large apps and Enable autosync for app-of-apps.
  app-of-apps/app-of-apps-curator.yaml
  app-of-apps/app-of-apps-infra.yaml
  app-of-apps/app-of-apps-zero.yaml
  envs/moc/curator/cluster-management/cluster-resources.yaml
  envs/moc/infra/cluster-management/cluster-resources.yaml
  envs/moc/zero/cluster-management/cluster-resources.yaml
  envs/moc/zero/cluster-management/kfdefs.yaml
Labels: approved, lgtm, size/M

#142 Use different overlay for thoth investigator
  envs/moc/zero/thoth/test/test-thoth-investigator.yaml
Labels: approved, lgtm, size/XS

#141 feat: Add openshift-acme app
  envs/moc/zero/operate-first/acme-operator.yaml
  envs/moc/zero/operate-first/kustomization.yaml
Labels: approved, lgtm, size/S

#143 Add jh idle culler app.
  envs/moc/zero/operate-first/jh-idle-culler.yaml
  envs/moc/zero/operate-first/kustomization.yaml
Labels: approved

#146 update the prow resource limits
  .prow.yaml
Labels: approved, lgtm, size/S

#147 support thoth-monitoring deployment with argocd
  envs/moc/zero/thoth/prod/kustomization.yaml
  envs/moc/zero/thoth/prod/prod-thoth-monitoring.yaml
Labels: approved, lgtm, size/S
