Repository operate-first/argocd-apps, pull requests merged in 2021-04, with the labels that each got.

#126 include thoth components for test cluster
  envs/moc/zero/thoth/kustomization.yaml
  envs/moc/zero/thoth/test/core-test.yaml
  envs/moc/zero/thoth/test/kustomization.yaml
  envs/moc/zero/thoth/test/test-thoth-advise-reporter.yaml
  envs/moc/zero/thoth/test/test-thoth-adviser.yaml
  envs/moc/zero/thoth/test/test-thoth-amun-api.yaml
  envs/moc/zero/thoth/test/test-thoth-chat-notification.yaml
  envs/moc/zero/thoth/test/test-thoth-cve-update.yaml
  envs/moc/zero/thoth/test/test-thoth-graph-backup.yaml
  envs/moc/zero/thoth/test/test-thoth-graph-refresh.yaml
  envs/moc/zero/thoth/test/test-thoth-graph-sync.yaml
  envs/moc/zero/thoth/test/test-thoth-investigator.yaml
  envs/moc/zero/thoth/test/test-thoth-kebechet.yaml
  envs/moc/zero/thoth/test/test-thoth-management-api.yaml
  envs/moc/zero/thoth/test/test-thoth-metrics-exporter.yaml
  envs/moc/zero/thoth/test/test-thoth-mi.yaml
  envs/moc/zero/thoth/test/test-thoth-package-extract.yaml
  envs/moc/zero/thoth/test/test-thoth-package-releases.yaml
  envs/moc/zero/thoth/test/test-thoth-package-update.yaml
  envs/moc/zero/thoth/test/test-thoth-prescription-sync.yaml
  envs/moc/zero/thoth/test/test-thoth-revsolver.yaml
  envs/moc/zero/thoth/test/test-thoth-security-indicators.yaml
  envs/moc/zero/thoth/test/test-thoth-solver.yaml
  envs/moc/zero/thoth/test/test-thoth-user-api.yaml
Labels: approved, lgtm, size/L

#127 feat: Add slack-first bot ArgoCD app
  envs/moc/zero/operate-first/kustomization.yaml
  envs/moc/zero/operate-first/slack-first.yaml
Labels: approved, size/S

#128 Remove unnecessary odh apps.
  envs/moc/zero/operate-first/argo.yaml
  envs/moc/zero/operate-first/dashboard.yaml
  envs/moc/zero/operate-first/datacatalog.yaml
  envs/moc/zero/operate-first/jupyterhub-stage.yaml
  envs/moc/zero/operate-first/jupyterhub.yaml
  envs/moc/zero/operate-first/kafka.yaml
  envs/moc/zero/operate-first/kustomization.yaml
  envs/moc/zero/operate-first/monitoring.yaml
  envs/moc/zero/operate-first/superset.yaml
Labels: approved, lgtm, size/L

#129 add apicurio
  envs/moc/zero/apicurio/kustomization.yaml
  envs/moc/zero/apicurio/registry.yml
  envs/moc/zero/kustomization.yaml
Labels: approved, lgtm, ok-to-test, size/S

#131 chore: Turn off ODH operator autosync
  envs/moc/zero/operate-first/odh-operator.yaml
Labels: approved, size/XS

#130 fix: Apicurio app to use default branch
  envs/moc/zero/apicurio/registry.yml
Labels: approved, lgtm, size/XS
